/* tslint:disable */
/* eslint-disable */
/**
 * int100grammer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AppControllerGetAllUsers200ResponseAllOf } from './app-controller-get-all-users200-response-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { PaginatedDto } from './paginated-dto';
// May contain unused imports in some cases
// @ts-ignore
import { UserEntity } from './user-entity';

/**
 * @type AppControllerGetAllUsers200Response
 * @export
 */
export type AppControllerGetAllUsers200Response = AppControllerGetAllUsers200ResponseAllOf & PaginatedDto;


