/* tslint:disable */
/* eslint-disable */
/**
 * int100grammer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserEntity } from './user-entity';

/**
 * 
 * @export
 * @interface AppControllerGetAllUsers200ResponseAllOf
 */
export interface AppControllerGetAllUsers200ResponseAllOf {
    /**
     * 
     * @type {Array<UserEntity>}
     * @memberof AppControllerGetAllUsers200ResponseAllOf
     */
    'results'?: Array<UserEntity>;
}

