/* tslint:disable */
/* eslint-disable */
/**
 * int100grammer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserEntity
 */
export interface UserEntity {
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'fullName': string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof UserEntity
     */
    'followers': number;
    /**
     * 
     * @type {number}
     * @memberof UserEntity
     */
    'following': number;
    /**
     * 
     * @type {number}
     * @memberof UserEntity
     */
    'postsAmount': number;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'lastPost': string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'phone': string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'site': string;
    /**
     * 
     * @type {boolean}
     * @memberof UserEntity
     */
    'potentiallyBusiness': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserEntity
     */
    'business': boolean;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'businessCategory': string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'countryCode': string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'countryReason': string;
}

